config/routes.rb
Rails.application.routes.draw do
 
  get  '/signup',  to: 'trainers#new'
  post '/signup',  to: 'trainers#create'

  root 'trainers#index'

  resources :trainers

  resources :tokimons


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tokimon.rb
class Tokimon < ApplicationRecord
	belongs_to :trainer
	validates :name, presence: true, length: { maximum: 20 }
	validates :height, presence: true, length: { maximum: 4 }
	validates :weight, presence: true, length: { maximum: 4 }
	validates :fire, presence: true, :numericality => { :greater_than_or_equal_to => 0, :less_than_or_equal_to => 100 }
	validates :fight, presence: true, :numericality => { :greater_than_or_equal_to => 0, :less_than_or_equal_to => 100 }
	validates :fly, presence: true, :numericality => { :greater_than_or_equal_to => 0, :less_than_or_equal_to => 100 }
	validates :water, presence: true, :numericality => { :greater_than_or_equal_to => 0, :less_than_or_equal_to => 100 }
	validates :electric, presence: true, :numericality => { :greater_than_or_equal_to => 0, :less_than_or_equal_to => 100 }
	validates :frozon, presence: true, :numericality => { :greater_than_or_equal_to => 0, :less_than_or_equal_to => 100 }
	validates :trainer_id, presence: true
	
end

app/models/trainer.rb
class Trainer < ApplicationRecord
	has_many :tokimons, dependent: :destroy
	validates :name, presence: true, length: { maximum: 20 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX },
				uniqueness: { case_sensitive: false}
	validates :age, presence: true, :numericality => { :greater_than_or_equal_to => 0, :less_than_or_equal_to => 100 }
	validates :height, presence: true, length: { maximum: 20 }
	validates :weight, presence: true, length: { maximum: 20 }
	
	validates :address, presence: true, length: { maximum: 100 }





end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tokimons_controller.rb
class TokimonsController < ApplicationController
  def index
    @tokimons = Tokimon.all
  end

  def show
    @tokimon = Tokimon.find(params[:id])
    @trainer = @tokimon.trainer
    @total = @tokimon.fire + @tokimon.fight + @tokimon.fly + @tokimon.water + @tokimon.electric + @tokimon.frozon
  end

  def new
    
    @tokimon = Tokimon.new
  end

  def create
    @tokimon = Tokimon.new(tokimon_params)
    @trainer = Trainer.find(@tokimon.trainer_id)
    
    if @tokimon.save
      @tokimon.total = @tokimon.fire + @tokimon.fight + @tokimon.fly + @tokimon.water + @tokimon.electric + @tokimon.frozon
      @tokimon.save
      flash[:info] = "tokimon created successful!"
      redirect_to @trainer
    else
      render 'new'
    end
  end

  def edit
    @tokimon = Tokimon.find(params[:id])
  end

  def update
     @tokimon = Tokimon.find(params[:id])
     
    if @tokimon.update_attributes(tokimon_params)
         @trainer = Trainer.find(@tokimon.trainer_id)
         @tokimon.total = @tokimon.fire + @tokimon.fight + @tokimon.fly + @tokimon.water + @tokimon.electric + @tokimon.frozon
         @tokimon.save
         flash[:success] = "Profile updated successfully"
         redirect_to @trainer
    else
      render 'edit'
    end
  end

  def destroy
    id = Tokimon.find(params[:id]).trainer_id
    @trainer = Trainer.find(id)
    Tokimon.find(params[:id]).destroy
    flash[:success] = "Tokimon deleted successfully"
    redirect_to @trainer
  end
private
    def tokimon_params
      params.require(:tokimon).permit(:name, :weight, :height, 
        :fly, :fight, :fire, :water, :electric, :frozon, :trainer_id)
    end



end

app/controllers/trainers_controller.rb
class TrainersController < ApplicationController
  def index
    @trainers = Trainer.all

  end

  def show
    @trainer = Trainer.find(params[:id])
    @tokimons = @trainer.tokimons.all
    @count = @trainer.tokimons.count / 3
    @trainer.update_attribute(:level, @count)
  end

  def new
    @trainer = Trainer.new

  end

  def create
    @trainer = Trainer.new(trainer_params)
    if @trainer.save
      flash[:info] = "Trainer created successfully!"
      redirect_to @trainer
    else
      render 'new'
    end
  end

  def edit
    @trainer = Trainer.find(params[:id])
  end

  def update
    @trainer = Trainer.find(params[:id])
    if @trainer.update_attributes(trainer_params)
      flash[:success] = "Profile updated successfully!"
      redirect_to @trainer
    else
      render 'edit'
    end

  end

  def destroy
    Trainer.find(params[:id]).destroy
    flash[:success] = "Trainer deleted successfully!"
    redirect_to trainers_url
  end

  private
    def trainer_params
      params.require(:trainer).permit(:name, :age, :height, :weight, :level, :address, :email)
    end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tokemons_helper.rb
module TokemonsHelper
end

app/helpers/trainers_helper.rb
module TrainersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
   
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">

        <%= link_to "Home", root_url, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Trainers",   root_url %></li>
            <li><%= link_to "Tokimons", tokimons_path %></li>
             <li><%= link_to "Create a new tokimon", new_tokimon_path %></li>
            <li><%= link_to "Help",   'http://guides.rubyonrails.org/getting_started.html' %></li>
           
          </ul>
        </nav>
      </div>
    </header>
    <div class="container">
    	<% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/tokimons/_tokimon.html.erb
<table style="width:100%">
<thead>
	<tr>
		<th>Name</th>
		<th>Height</th>
		<th>Weight</th>
		<th>Fly</th>
		<th>Fight</th>
		<th>Fire</th>
		<th>Water</th>
		<th>Electric</th>
		<th>Frozon</th>
		<th>Total</th>
		<th></th>
		<th></th>
		<th></th>
	</tr>
	</thead>

	<tbody>
	<% @tokimons.each do |tokimon| %>
	<tr>
		<td><%= tokimon.name %></td>
		<td><%= tokimon.height %></td>
		<td><%= tokimon.weight %></td>
		<td><%= tokimon.fly %></td>
		<td><%= tokimon.fight %></td>
		<td><%= tokimon.fire %></td>
		<td><%= tokimon.water %></td>
		<td><%= tokimon.electric %></td>
		<td><%= tokimon.frozon %></td>
		<td><%= tokimon.fly + tokimon.fight + tokimon.fire + tokimon.water + tokimon.electric + tokimon.frozon %></td>
		<td><%= link_to 'Profile', tokimon %> </td>
		<td><%= link_to 'Edit', edit_tokimon_path(tokimon) %> </td>
		<td><%= link_to 'Delete', tokimon, method: :delete, data: { confirm: 'Are you sure you want to delete the cute tokimon?'} %> </td>
	</tr> 
	<% end %>
	</tbody>
</table>
<br>
<br>
<h3>Bar chart(in the order of names)</h3>
<%= bar_chart Tokimon.group(:name).sum(:total) %>

app/views/tokimons/destroy.html.erb
<h1>Tokemons#destroy</h1>
<p>Find me in app/views/tokemons/destroy.html.erb</p>

app/views/tokimons/edit.html.erb
<% provide(:title, 'Eidt Tokimon') %>
<h1>Edit the Tokimon</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@tokimon) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :weight %>
      <%= f.text_field :weight , class: 'form-control' %>

      <%= f.label :height %>
      <%= f.text_field :height , class: 'form-control' %>

      <%= f.label :fly %>
      <%= f.text_field :fly , class: 'form-control' %>

      <%= f.label :fight %>
      <%= f.text_field :fight , class: 'form-control' %>

      <%= f.label :fire %>
      <%= f.text_field :fire , class: 'form-control' %>

      <%= f.label :water %>
      <%= f.text_field :water , class: 'form-control' %>

      <%= f.label :electric %>
      <%= f.text_field :electric , class: 'form-control' %>

      <%= f.label :frozon %>
      <%= f.text_field :frozon , class: 'form-control' %>

      <br>
      <p>Change it's trainer</p>
      
      <select name="tokimon[trainer_id]">
    <% Trainer.all.each do |trainer| %>
        <option value="<%= trainer.id %>"><%= trainer.name %></option>
    <% end %>
</select>
<br>
<br>

      

      <%= f.submit "Finish editing", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/tokimons/index.html.erb
<% provide(:title, "Index_tokimon") %>

<h1>The list of Tokimons</h1>

<table style="width:80%">
<thead>
	<tr>
		<th>Name</th>
		<th>Height</th>
		<th>Weight</th>
		<th>Fly</th>
		<th>Fight</th>
		<th>Fire</th>
		<th>Water</th>
		<th>Electric</th>
		<th>Frozon</th>
		<th>Total</th>
		<th></th>
		<th></th>

	</tr>
	</thead>

	<tbody>
	<% @tokimons.each do |tokimon| %>
	<tr>
		<td><%= tokimon.name %></td>
		<td><%= tokimon.height %></td>
		<td><%= tokimon.weight %></td>
		<td><%= tokimon.fly %></td>
		<td><%= tokimon.fight %></td>
		<td><%= tokimon.fire %></td>
		<td><%= tokimon.water %></td>
		<td><%= tokimon.electric %></td>
		<td><%= tokimon.frozon %></td>
		<td><%= tokimon.fire + tokimon.fight + tokimon.fly + tokimon.water + tokimon.electric + tokimon.frozon %></td>
		<td><%= link_to "Profile", tokimon %></td>
		<td><%= link_to "Delete", tokimon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	</tr> 
	<% end %>
	</tbody>
</table>

<br>

<%= link_to "create new tokimon!", new_tokimon_path, class: "btn btn-lg btn-primary" %>

<%= bar_chart Tokimon.group(:name).sum(:total) %>

app/views/tokimons/new.html.erb
<% provide(:title, 'New Tokimon') %>
<h1>Create new Tokimon</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@tokimon) do |f| %>

      <%= render 'shared/error_messages', object: f.object %>
    	
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :weight %>
      <%= f.text_field :weight , class: 'form-control' %>

      <%= f.label :height %>
      <%= f.text_field :height , class: 'form-control' %>

      <%= f.label :fly %>
      <%= f.text_field :fly , class: 'form-control' %>

      <%= f.label :fight %>
      <%= f.text_field :fight , class: 'form-control' %>

      <%= f.label :fire %>
      <%= f.text_field :fire , class: 'form-control' %>

      <%= f.label :water %>
      <%= f.text_field :water , class: 'form-control' %>

      <%= f.label :electric %>
      <%= f.text_field :electric , class: 'form-control' %>

      <%= f.label :frozon %>
      <%= f.text_field :frozon , class: 'form-control' %>

      <br>
      <p style="font-size:150%;">Choose its trainer</p>
      
      <select name="tokimon[trainer_id]" style="font-size:300%;">
    <% Trainer.all.each do |trainer| %>
        <option value="<%= trainer.id %>" style="font-size:250%;"><%= trainer.name %></option>
    <% end %>
</select>
<br>
<br>

      

      <%= f.submit "Create a new Tokimon", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/tokimons/show.html.erb
<% provide(:title, "Show-Tokimon") %>
<div class="col-md-6 col-md-offset-3">
<h1>The Tokemon's profile</h1>

<p id="notice"><%= notice %></p>

<p>
<strong>Name: </strong>
<%= @tokimon.name %>
	
</p>


<p>
<strong>Height: </strong>
<%= @tokimon.height %>
	
</p>

<p>
<strong>Weight: </strong>
<%= @tokimon.weight %>
	
</p>

<p>
<strong>Fly: </strong>
<%= @tokimon.fly %>
	
</p>

<p>
<strong>Fight: </strong>
<%= @tokimon.fight %>
	
</p>

<p>
<strong>Fire: </strong>
<%= @tokimon.fire %>
	
</p>

<p>
<strong>Water: </strong>
<%= @tokimon.water %>
	
</p>

<p>
<strong>Electric: </strong>
<%= @tokimon.electric %>
	
</p>

<p>
<strong>Frozon: </strong>
<%= @tokimon.frozon %>
	
</p>

<p>
<strong>Total: </strong>
<%= @total %>
	
</p>

<%= link_to 'Back to its trainer', @trainer, class: "btn btn-primary" %> |
<%= link_to 'Back to the list', tokimons_path, class: "btn btn-primary" %> |
<%= link_to 'Edit', edit_tokimon_path(@tokimon), class: "btn btn-primary" %> 
</div>

app/views/tokimons/update.html.erb
<h1>Tokemons#update</h1>
<p>Find me in app/views/tokemons/update.html.erb</p>

app/views/trainers/edit.html.erb
<% provide(:title, 'Edit the Trainer') %>
<h1>Edit the trainer</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@trainer) do |f| %>
    	<%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :age %>
      <%= f.text_field :age , class: 'form-control' %>

      <%= f.label :height %>
      <%= f.text_field :height , class: 'form-control' %>

      <%= f.label :weight %>
      <%= f.text_field :weight , class: 'form-control' %>


      <%= f.label :address %>
      <%= f.text_field :address , class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email , class: 'form-control' %>

      

      

      <%= f.submit "edit the trainer", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/trainers/index.html.erb
<% provide(:title, "Index") %>

<h1>Welcome to the amazing Tokimon World!</h1>

<table style="width:100%">
<thead>
	<tr>
		<th>Name</th>
		<th>Age</th>
		<th>Height</th>
		<th>Weight</th>
		<th>Level</th>
		<th>Address</th>
		<th>Email</th>
		<th></th>
		<th></th>
		

	</tr>
	</thead>

	<tbody>
	<% @trainers.each do |trainer| %>
	<tr>
		<td><%= trainer.name %></td>
		<td><%= trainer.age %></td>
		<td><%= trainer.height %></td>
		<td><%= trainer.weight %></td>
		<td><%= trainer.level %></td>
		<td><%= trainer.address %></td>
		<td><%= trainer.email %></td>
		<td><%= link_to "Profile", trainer %></td>
		<td><%= link_to "Delete", trainer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	</tr> 
	<% end %>
	</tbody>
</table>

<br>

<%= link_to "create a new trainer!", new_trainer_path, class: "btn btn-lg btn-primary" %>

<br>
<br>
<h3>Bar chart for levels: </h3>
<%= bar_chart Trainer.group(:name).sum(:level) %>

app/views/trainers/new.html.erb
<% provide(:title, 'New Trainer') %>
<h1>Create new trainer</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@trainer) do |f| %>
    	<%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :age %>
      <%= f.text_field :age , class: 'form-control' %>

      <%= f.label :height %>
      <%= f.text_field :height , class: 'form-control' %>

      <%= f.label :weight %>
      <%= f.text_field :weight , class: 'form-control' %>

      

      <%= f.label :address %>
      <%= f.text_field :address , class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email , class: 'form-control' %>

      

      

      <%= f.submit "Create a new trainer", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/trainers/show.html.erb
<h1>The trainer's Profile</h1>

<p id="notice"><%= notice %></p>

<table align="center">
<p>
<strong>Name: </strong>
<%= @trainer.name %>
	
</p>

<p>
<strong>age: </strong>
<%= @trainer.age %>
	
</p>

<p>
<strong>Height: </strong>
<%= @trainer.height %>
	
</p>

<p>
<strong>Weight: </strong>
<%= @trainer.weight %>
	
</p>

<p>
<strong>Level: </strong>
<%= @trainer.level = @count %>
	
</p>

<p>
<strong>Address: </strong>
<%= @trainer.address %>
	
</p>

<p>
<strong>Email: </strong>
<%= @trainer.email %>
	
</p>


<%= link_to 'Edit', edit_trainer_path(@trainer), class: "btn btn-primary"%> |
<%= link_to 'Back', trainers_path, class: "btn btn-primary" %> |
<%= link_to 'Create a new tokimon', new_tokimon_path, class: "btn btn-primary" %>
<br>

<div class="col-md-8">
 
    <% if @trainer.tokimons.any? %>
      <h3> Total tokimons (<%= @trainer.tokimons.count %>)</h3>
      <ol class="tokimons">
        <%= render 'tokimons/tokimon' %>
      </ol>
      
    <% end %>
  </div>